In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [9]:
df = pd.read_csv('Fraud_Detection_Dataset.csv', nrows=10000)

In [14]:
df.shape

(10000, 12)

In [16]:
df.isnull().sum()

Transaction_ID                        0
User_ID                               0
Transaction_Amount                  493
Transaction_Type                      0
Time_of_Transaction                 518
Device_Used                         467
Location                            482
Previous_Fraudulent_Transactions      0
Account_Age                           0
Number_of_Transactions_Last_24H       0
Payment_Method                      483
Fraudulent                            0
dtype: int64

In [11]:
df.head()

Transaction_ID  User_ID  Transaction_Amount Transaction_Type  \
0             T1     4174             1292.76   ATM Withdrawal   
1             T2     4507             1554.58   ATM Withdrawal   
2             T3     1860             2395.02   ATM Withdrawal   
3             T4     2294              100.10     Bill Payment   
4             T5     2130             1490.50      POS Payment   

   Time_of_Transaction Device_Used       Location  \
0                 16.0      Tablet  San Francisco   
1                 13.0      Mobile       New York   
2                  NaN      Mobile            NaN   
3                 15.0     Desktop        Chicago   
4                 19.0      Mobile  San Francisco   

   Previous_Fraudulent_Transactions  Account_Age  \
0                                 0          119   
1                                 4           79   
2                                 3          115   
3                                 4            3   
4                                 2           57   

   Number_of_Transactions_Last_24H Payment_Method  Fraudulent  
0                               13     Debit Card           0  
1                                3    Credit Card           0  
2                                9            NaN           0  
3                                4            UPI           0  
4                                7    Credit Card           0

In [20]:
df.duplicated().sum()

0

In [32]:
def clean(data):
    data.drop(data.columns[[0,3,5,6,10]], inplace=True, axis=1)
    print("Shape after dropping categorical columns: ", data.shape)

    data.dropna(inplace=True)
    print("Shape afer removing null values: ", data.shape)

    data.drop_duplicates(inplace=True)
    print("Shape after dropping duplicates: ", data.shape)

    return data

In [34]:
df = clean(df)

Shape after dropping categorical columns:  (10000, 7)
Shape afer removing null values:  (9023, 7)
Shape after dropping duplicates:  (9023, 7)


In [36]:
df.head()

User_ID  Transaction_Amount  Time_of_Transaction  \
0     4174             1292.76                 16.0   
1     4507             1554.58                 13.0   
3     2294              100.10                 15.0   
4     2130             1490.50                 19.0   
5     2095             2372.04                 15.0   

   Previous_Fraudulent_Transactions  Account_Age  \
0                                 0          119   
1                                 4           79   
3                                 4            3   
4                                 2           57   
5                                 3           96   

   Number_of_Transactions_Last_24H  Fraudulent  
0                               13           0  
1                                3           0  
3                                4           0  
4                                7           0  
5                               14           0

In [38]:
X = df.drop(columns=['Fraudulent'])
Y = df['Fraudulent']

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=2, test_size=0.2)

X_train.shape, X_test.shape, y_train.shape

((7218, 6), (1805, 6), (7218,))

In [79]:
y_train = y_train.reset_index(drop=True)

In [81]:
def perceptron(X_train, y_train):
    X_train = np.insert(X_train, 0, 1, axis=1)
    weights = np.ones(X_train.shape[1])
    lr = 0.1

    for i in range(1000):
        j = np.random.randint(0,X_train.shape[0])
        y_hat = step(np.dot(X_train[j], weights))
        weights = weights + lr * (y_train.iloc[j] - y_hat) * X_train[j]

    return weights[0], weights[1:]

In [83]:
def step(z):
    return 1 if z>0 else 0

In [85]:
intercept_, coef_ = perceptron(X_train, y_train)

In [87]:
intercept_

1.6000000000000005

In [91]:
coef_

array([-205.1  , -749.767,    8.2  ,    3.9  ,   -4.5  ,    5.5  ])

In [95]:
lor = LogisticRegression(max_iter=1000)
lor.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [97]:
lor.intercept_

array([-3.27145036])

In [99]:
lor.coef_

array([[ 2.45345377e-05,  1.39838146e-05,  6.53008449e-03,
         6.39749280e-02,  3.88548410e-04, -9.33776188e-03]])